echo "You have several Node tools:"
echo " * mocha"
echo "You have several Docker tools alias you can use:"
echo " * Inspect the layers of a Docker image: dive <image-name>"
echo " * Run lazydocker in a container: ld"
