name: Docker Hub readme
on:
  push:
    branches: [master]
    paths:
      - README.md
      - .github/workflows/dockerhub-readme.yml
jobs:
  dockerhub-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Hub Readme
        uses: peter-evans/dockerhub-description@v3
        with:
          username: qmcgaw
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: qmcgaw/nodedevcontainer
