name: Docker build
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/pr.yml
      - shell/**
      - .dockerignore
      - Dockerfile
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker buildx build  \
            --progress plain \
            --platform=linux/amd64 \
            .
