name: Buildx release
on:
  release:
    types: [published]
    paths:
      - .github/workflows/release.yml
      - shell/**
      - .dockerignore
      - Dockerfile
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64 \
            --build-arg CREATED=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION=${GITHUB_REF##*/} \
            -t qmcgaw/nodedevcontainer:${GITHUB_REF##*/} \
            --push \
            .
